var level = {
    enemies:[
        {
            levelz : 1,
            enemyBlue : 12,
            scoreEnemyBlue:30,
            lineEnemyBlue:1,
            enemyRed : 0,
            scoreEnemyRed:50,
            lineEnemyRed:0,
            enemyGreen : 0,
            scoreEnemyGreen:100,
            lineEnemyGreen:0,
            speed : 0.5
        },
        {
            levelz : 2,
            enemyBlue : 12,
            scoreEnemyBlue:30,
            lineEnemyBlue:1,
            enemyRed : 0,
            scoreEnemyRed:50,
            lineEnemyRed:0,
            enemyGreen : 0,
            scoreEnemyGreen:100,
            lineEnemyGreen:0,
            speed : 0.3
        },
        {
            levelz : 3,
            enemyBlue : 12,
            scoreEnemyBlue:30,
            lineEnemyBlue:2,
            enemyRed : 0,
            scoreEnemyRed:50,
            lineEnemyRed:0,
            enemyGreen : 0,
            scoreEnemyGreen:100,
            lineEnemyGreen:0,
            speed : 0.5
        },
        {
            levelz : 4,
            enemyBlue : 12,
            scoreEnemyBlue:30,
            lineEnemyBlue:2,
            enemyRed : 0,
            scoreEnemyRed:50,
            lineEnemyRed:0,
            enemyGreen : 0,
            scoreEnemyGreen:100,
            lineEnemyGreen:0,
            speed : 0.3
        },
        {
            levelz : 5,
            enemyBlue : 12,
            scoreEnemyBlue:30,
            lineEnemyBlue:2,
            enemyRed : 12,
            scoreEnemyRed:50,
            lineEnemyRed:1,
            enemyGreen : 0,
            scoreEnemyGreen:100,
            lineEnemyGreen:0,
            speed : 0.5
        },
        {
            levelz : 6,
            enemyBlue : 12,
            scoreEnemyBlue:30,
            lineEnemyBlue:2,
            enemyRed : 12,
            scoreEnemyRed:50,
            lineEnemyRed:1,
            enemyGreen : 0,
            scoreEnemyGreen:100,
            lineEnemyGreen:0,
            speed : 0.3
        },
        {
            levelz : 7,
            enemyBlue : 12,
            scoreEnemyBlue:30,
            lineEnemyBlue:2,
            enemyRed : 12,
            scoreEnemyRed:50,
            lineEnemyRed:2,
            enemyGreen : 0,
            scoreEnemyGreen:100,
            lineEnemyGreen:0,
            speed : 0.5
        },
        {
            levelz : 8,
            enemyBlue : 12,
            scoreEnemyBlue:30,
            lineEnemyBlue:2,
            enemyRed : 12,
            scoreEnemyRed:50,
            lineEnemyRed:2,
            enemyGreen : 0,
            scoreEnemyGreen:100,
            lineEnemyGreen:0,
            speed : 0.3
        },
        {
            levelz : 9,
            enemyBlue : 12,
            scoreEnemyBlue:30,
            lineEnemyBlue:2,
            enemyRed : 12,
            scoreEnemyRed:50,
            lineEnemyRed:2,
            enemyGreen : 12,
            scoreEnemyGreen:100,
            lineEnemyGreen:1,
            speed : 0.5
        },
        {
            levelz : 10,
            enemyBlue : 12,
            scoreEnemyBlue:30,
            lineEnemyBlue:2,
            enemyRed : 12,
            scoreEnemyRed:50,
            lineEnemyRed:2,
            enemyGreen : 12,
            scoreEnemyGreen:100,
            lineEnemyGreen:1,
            speed : 0.3
        },
        {
            levelz : 11,
            enemyBlue : 12,
            scoreEnemyBlue:30,
            lineEnemyBlue:2,
            enemyRed : 12,
            scoreEnemyRed:50,
            lineEnemyRed:2,
            enemyGreen : 12,
            scoreEnemyGreen:100,
            lineEnemyGreen:2,
            speed : 0.5
        },
        {
            levelz : 12,
            enemyBlue : 12,
            scoreEnemyBlue:30,
            lineEnemyBlue:2,
            enemyRed : 12,
            scoreEnemyRed:50,
            lineEnemyRed:2,
            enemyGreen : 12,
            scoreEnemyGreen:100,
            lineEnemyGreen:2,
            speed : 0.3
        }
    
    ]
};